import { PACKING_ITEMS } from './constants';

const now = new Date();
const daysAgo = days => new Date(now.getTime() - days * 86400000).toISOString();
const daysFrom = days => new Date(now.getTime() + days * 86400000).toISOString();

export const seedOrders = [
  {
    id: 'seed-10091',
    external_order_id: 'WIX-10091',
    order_number: '10091',
    source: 'wix',
    customer_name: 'Arjun Mehta',
    phone: '+91 98765 43210',
    email: 'arjun@example.com',
    address_line1: '22 Indiranagar 12th Main',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    country: 'IN',
    bike_model: 'Royal Enfield Himalayan 450',
    product_variant: 'HMT Cruise Kit - Himalayan 450',
    quantity: 1,
    payment_status: 'paid',
    order_value: 12999,
    currency: 'INR',
    order_date: daysAgo(0),
    internal_status: 'awaiting_packing',
    shipment_status: 'not_booked',
    installation_status: 'not_contacted',
    installation_method: 'unknown',
    feedback_status: 'feedback_pending',
    assigned_operator: 'Nisha',
    tags: ['wix', 'priority'],
    notes: 'Customer requested WhatsApp tracking update.',
    courier: '',
    awb_number: '',
    tracking_url: '',
    chatwoot_contact_id: 'cw-4389',
    chatwoot_conversation_id: 'conv-7812',
    last_communication_at: daysAgo(0),
    last_message_type: 'order-confirmation'
  },
  {
    id: 'seed-10088',
    external_order_id: 'AMZ-406-2281443',
    order_number: 'AMZ-2281443',
    source: 'amazon',
    customer_name: 'Sneha Kulkarni',
    phone: '+91 99887 76655',
    email: 'sneha@example.com',
    address_line1: 'A-503 Green Park Society',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    country: 'IN',
    bike_model: 'KTM Adventure 390',
    product_variant: 'HMT Cruise Kit - KTM 390 Adv',
    quantity: 1,
    payment_status: 'paid',
    order_value: 13999,
    currency: 'INR',
    order_date: daysAgo(2),
    internal_status: 'pickup_pending',
    shipment_status: 'pickup_pending',
    installation_status: 'not_contacted',
    installation_method: 'unknown',
    feedback_status: 'feedback_pending',
    assigned_operator: 'Ravi',
    tags: ['amazon'],
    notes: 'Amazon address line corrected manually.',
    courier: 'delhivery',
    awb_number: 'DLV88392011',
    tracking_url: 'https://www.delhivery.com/track/package/DLV88392011',
    chatwoot_contact_id: '',
    chatwoot_conversation_id: '',
    last_communication_at: daysAgo(1),
    last_message_type: 'tracking-link'
  },
  {
    id: 'seed-10072',
    external_order_id: 'MAN-10072',
    order_number: 'MAN-10072',
    source: 'manual',
    customer_name: 'Rohan Dsouza',
    phone: '+91 90909 11223',
    email: 'rohan@example.com',
    address_line1: 'Villa 14, Miramar Road',
    city: 'Panaji',
    state: 'Goa',
    pincode: '403001',
    country: 'IN',
    bike_model: 'Triumph Scrambler 400X',
    product_variant: 'HMT Cruise Kit - Scrambler 400X',
    quantity: 1,
    payment_status: 'paid',
    order_value: 14999,
    currency: 'INR',
    order_date: daysAgo(6),
    internal_status: 'installation_pending',
    shipment_status: 'delivered',
    installation_status: 'guide_sent',
    installation_method: 'diy',
    feedback_status: 'feedback_pending',
    assigned_operator: 'Anika',
    tags: ['manual', 'install-help'],
    notes: 'Needs video install guide in English.',
    courier: 'fedex',
    awb_number: 'FDX90112230',
    tracking_url: 'https://www.fedex.com/fedextrack/?trknbr=FDX90112230',
    chatwoot_contact_id: 'cw-4492',
    chatwoot_conversation_id: 'conv-8022',
    last_communication_at: daysAgo(1),
    last_message_type: 'installation-guide'
  },
  {
    id: 'seed-10060',
    external_order_id: 'WIX-10060',
    order_number: '10060',
    source: 'wix',
    customer_name: 'Karan Malhotra',
    phone: '+91 91234 56780',
    email: 'karan@example.com',
    address_line1: '91 Sector 45',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122003',
    country: 'IN',
    bike_model: 'BMW G 310 GS',
    product_variant: 'HMT Cruise Kit - BMW G 310',
    quantity: 1,
    payment_status: 'paid',
    order_value: 15999,
    currency: 'INR',
    order_date: daysAgo(12),
    internal_status: 'issue_reported',
    shipment_status: 'delivered',
    installation_status: 'installation_issue',
    installation_method: 'nearby_garage',
    garage_name: 'Speedline Moto Works',
    garage_contact_person: 'Manoj',
    garage_phone: '+91 98111 22334',
    garage_address: 'Sector 45 market road',
    garage_city: 'Gurugram',
    garage_state: 'Haryana',
    feedback_status: 'issue_escalated',
    assigned_operator: 'Nisha',
    tags: ['support', 'warranty_case'],
    notes: 'Throttle calibration issue after installation.',
    courier: 'shree_maruti',
    awb_number: 'SMC5530091',
    tracking_url: 'https://trackcourier.io/shree-maruti/SMC5530091',
    chatwoot_contact_id: 'cw-4311',
    chatwoot_conversation_id: 'conv-7901',
    last_communication_at: daysAgo(0),
    last_message_type: 'support-follow-up'
  }
];

export const seedTasks = [
  {
    id: 'task-1',
    title: 'Verify new Wix order',
    order_id: 'seed-10091',
    order_number: '10091',
    assigned_operator: 'Nisha',
    due_date: daysFrom(0),
    priority: 'high',
    status: 'open',
    notes: 'Confirm bike model and address before packing.'
  },
  {
    id: 'task-2',
    title: 'Follow up after failed pickup',
    order_id: 'seed-10088',
    order_number: 'AMZ-2281443',
    assigned_operator: 'Ravi',
    due_date: daysFrom(0),
    priority: 'medium',
    status: 'in_progress',
    notes: 'Courier pickup pending since yesterday.'
  },
  {
    id: 'task-3',
    title: 'Send installation video',
    order_id: 'seed-10072',
    order_number: 'MAN-10072',
    assigned_operator: 'Anika',
    due_date: daysFrom(1),
    priority: 'medium',
    status: 'open',
    notes: 'Customer asked for English guide.'
  },
  {
    id: 'task-4',
    title: 'Resolve support issue',
    order_id: 'seed-10060',
    order_number: '10060',
    assigned_operator: 'Nisha',
    due_date: daysFrom(0),
    priority: 'urgent',
    status: 'open',
    notes: 'Create warranty case if calibration cannot be fixed remotely.'
  }
];

export const seedIntegrationErrors = [
  {
    id: 'err-1',
    integration: 'amazon',
    operation: 'fetch-orders',
    status: 'open',
    message: 'Amazon order AMZ-406-2281443 was missing address line 2.',
    occurred_at: daysAgo(2),
    payload: { orderId: 'AMZ-406-2281443' }
  },
  {
    id: 'err-2',
    integration: 'delhivery',
    operation: 'book-shipment',
    status: 'resolved',
    message: 'Invalid pincode rejected by courier validation.',
    occurred_at: daysAgo(4),
    payload: { pincode: '000000' }
  }
];

export const seedTimeline = order => [
  { id: `${order.id}-1`, event_type: 'order_imported', old_value: '', new_value: order.source, notes: 'Order stored in Supabase CRM state.', created_at: order.order_date, actor_name: 'System' },
  { id: `${order.id}-2`, event_type: 'details_verified', old_value: 'new', new_value: order.internal_status, notes: order.notes, created_at: order.last_communication_at || order.order_date, actor_name: order.assigned_operator || 'Operator' }
];

export const seedPackingChecklist = order => PACKING_ITEMS.map((item, index) => ({
  id: `${order.id}-pack-${index}`,
  order_id: order.id,
  item_name: item,
  is_packed: ['packed', 'pickup_pending', 'in_transit', 'delivered', 'installation_pending', 'completed', 'issue_reported'].includes(order.internal_status),
  checked_at: order.order_date
}));
