'use client';

import { useState } from 'react';

export function FinanceWorkspace({ overview, section = 'finance' }) {
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  async function submit(resource, event, transform = form => Object.fromEntries(form.entries())) {
    event.preventDefault(); setBusy(true); setNotice('');
    const response = await fetch(`/api/finance/${resource}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(transform(new FormData(event.currentTarget))) });
    const payload = await response.json(); setBusy(false);
    setNotice(response.ok ? 'Saved. Refreshing the workspace…' : payload.error || 'Could not save.');
    if (response.ok) setTimeout(() => window.location.reload(), 400);
  }
  const items = overview.items || [];
  const itemOptions = items.map(item => <option value={item.id} key={item.id}>{item.sku} · {item.product_name}</option>);
  return <>
    {notice ? <p className="muted" role="status">{notice}</p> : null}
    {section === 'finance' ? <>
      <MetricGrid dashboard={overview.dashboard} />
      <div className="toolbar" style={{ marginBottom: 16 }}><form onSubmit={event => submit('sales-sync', event)}><button disabled={busy}>Sync sales invoices from orders</button></form><a className="button secondary" href="/api/finance/export?type=pnl">Download P&amp;L CSV</a><a className="button secondary" href="/api/finance/export?type=sales">GST sales CSV</a><a className="button secondary" href="/api/finance/export?type=purchases">Purchase / ITC CSV</a><a className="button secondary" href="/api/finance/export?type=inventory">Inventory valuation CSV</a></div>
      <div className="twoColumn">
        <Panel title="Create vendor"><form className="formGrid" onSubmit={event => submit('vendors', event)}><Field name="name" label="Vendor name" required /><Field name="gstin" label="GSTIN" /><Field name="email" label="Email" type="email" /><Field name="payment_terms_days" label="Payment terms (days)" type="number" value="30" /><button disabled={busy}>Add vendor</button></form></Panel>
        <Panel title="Record bill or expense"><form className="formGrid" onSubmit={event => submit('documents', event, form => ({ ...Object.fromEntries(form.entries()), lines: [{ description: form.get('description'), quantity: 1, unit_price: Number(form.get('amount')), tax_rate: Number(form.get('tax_rate') || 0) }] }))}><label><span>Document type</span><select name="document_type" defaultValue="purchase_bill"><option value="purchase_bill">Purchase bill</option><option value="expense">Expense</option><option value="payroll">Payroll journal</option><option value="sales_invoice">Sales invoice</option><option value="credit_note">Credit note</option></select></label><Field name="document_number" label="Invoice/reference" required /><Field name="document_date" label="Date" type="date" /><Field name="amount" label="Amount" type="number" required /><Field name="tax_rate" label="GST %" type="number" value="0" /><Field name="description" label="Description" required /><button disabled={busy}>Save document</button></form></Panel>
        <Panel title="Submit reimbursement"><form className="formGrid" onSubmit={event => submit('reimbursements', event)}><Field name="business_purpose" label="Business purpose" required /><Field name="amount" label="Amount" type="number" required /><Field name="document_date" label="Expense date" type="date" /><button disabled={busy}>Submit claim</button></form></Panel>
        <Panel title="Bank statement import"><form className="formGrid" onSubmit={event => submit('bank-imports', event, form => ({ bank_account_id: form.get('bank_account_id'), filename: form.get('filename'), source_type: 'manual', transactions: JSON.parse(form.get('transactions') || '[]') }))}><Field name="bank_account_id" label="Bank account ID" required /><Field name="filename" label="Statement filename" value="statement.csv" /><label className="full"><span>Transaction JSON</span><textarea name="transactions" placeholder={'[{"transaction_date":"2026-08-01","description":"UPI receipt","credit":1000,"debit":0}]'} required /></label><button disabled={busy}>Import transactions</button></form><p className="muted">CSV/XLSX/PDF ingestion routes into this validated transaction format after parser/OCR review.</p></Panel>
      </div>
      <Panel title="Recent financial documents"><DocumentTable rows={overview.documents} /></Panel>
      <Panel title="Reimbursement queue"><ClaimTable rows={overview.claims} onAction={(id, action) => submit('reimbursements', { preventDefault() {}, currentTarget: { } }, () => ({ id, action }))} /></Panel>
    </> : null}
    {section === 'inventory' ? <>
      <MetricGrid dashboard={overview.dashboard} inventory />
      <div className="twoColumn"><Panel title="Create inventory item"><form className="formGrid" onSubmit={event => submit('items', event)}><Field name="sku" label="SKU" required /><Field name="product_name" label="Item name" required /><label><span>Item type</span><select name="item_type"><option value="raw_material">Raw material</option><option value="consumable">Consumable</option><option value="packaging">Packaging</option><option value="subassembly">Subassembly</option><option value="finished_good">Finished good</option><option value="service">Service</option><option value="non_stock">Non-stock</option></select></label><Field name="base_uom" label="UOM" value="EA" /><Field name="average_cost" label="Starting cost" type="number" value="0" /><Field name="reorder_point" label="Reorder point" type="number" value="0" /><button disabled={busy}>Create item</button></form></Panel>
      <Panel title="Record stock movement"><form className="formGrid" onSubmit={event => submit('movements', event)}><label><span>Item</span><select name="inventory_item_id" required><option value="">Select item</option>{itemOptions}</select></label><label><span>Movement</span><select name="movement_type"><option value="receipt">Purchase receipt</option><option value="issue">Issue</option><option value="adjustment">Adjustment</option><option value="return_in">Customer return</option><option value="return_out">Supplier return</option><option value="scrap">Scrap</option></select></label><Field name="quantity" label="Quantity (+/-)" type="number" required /><Field name="unit_cost" label="Unit cost" type="number" value="0" /><Field name="stock_location_id" label="Bin/location ID" /><button disabled={busy}>Post movement</button></form></Panel></div>
      <Panel title="Inventory and replenishment"><InventoryTable items={items} /></Panel>
    </> : null}
    {section === 'manufacturing' ? <>
      <div className="twoColumn"><Panel title="Create BOM revision"><form className="formGrid" onSubmit={event => submit('boms', event, form => ({ finished_item_id: form.get('finished_item_id'), revision: form.get('revision'), quantity_basis: Number(form.get('quantity_basis') || 1), expected_yield: Number(form.get('expected_yield') || 1), instructions: form.get('instructions'), lines: JSON.parse(form.get('lines') || '[]') }))}><label><span>Finished item</span><select name="finished_item_id" required><option value="">Select finished item</option>{itemOptions}</select></label><Field name="revision" label="Revision" required value="A" /><Field name="quantity_basis" label="Build quantity" type="number" value="1" /><Field name="expected_yield" label="Expected yield" type="number" value="1" /><label className="full"><span>Components JSON</span><textarea name="lines" required placeholder={'[{"component_item_id":"uuid","quantity":2,"uom":"EA","scrap_percent":0}]'} /></label><Field name="instructions" label="Build instructions" /><button disabled={busy}>Save BOM draft</button></form></Panel>
      <Panel title="Create work order"><form className="formGrid" onSubmit={event => submit('work-orders', event)}><label><span>Approved BOM</span><select name="bom_id" required><option value="">Select BOM</option>{(overview.boms || []).filter(bom => bom.status === 'approved').map(bom => <option key={bom.id} value={bom.id}>{bom.inventory_items?.sku || bom.finished_item_id} rev {bom.revision}</option>)}</select></label><Field name="planned_quantity" label="Planned quantity" type="number" value="1" required /><Field name="due_date" label="Due date" type="date" /><Field name="output_location_id" label="Output bin ID" /><button disabled={busy}>Create work order</button></form></Panel></div>
      <Panel title="BOM revisions"><BomTable rows={overview.boms || []} /></Panel>
      <Panel title="Work orders"><WorkOrderTable rows={overview.workOrders || []} /></Panel>
    </> : null}
  </>;
}

function Panel({ title, children }) { return <section className="panel"><div className="panelHeader"><h2>{title}</h2></div><div className="panelBody">{children}</div></section>; }
function Field({ name, label, type = 'text', value, required = false }) { return <label><span>{label}</span><input name={name} type={type} defaultValue={value} required={required} /></label>; }
function MetricGrid({ dashboard = {}, inventory }) { const entries = inventory ? [['Low stock', dashboard.lowStock], ['Open work orders', dashboard.openWorkOrders], ['Unreconciled bank', dashboard.unreconciled]] : [['Revenue', currency(dashboard.revenue)], ['Expenses', currency(dashboard.expenses)], ['Management P&L', currency(dashboard.grossMargin)], ['Cash movement', currency(dashboard.cash)], ['Payables', currency(dashboard.payables)], ['Unreconciled bank', dashboard.unreconciled]]; return <section className="metricGrid">{entries.map(([label, value]) => <article className="card metric" key={label}><span>{label}</span><strong>{value ?? 0}</strong></article>)}</section>; }
function DocumentTable({ rows = [] }) { return <table><thead><tr><th>Type</th><th>Reference</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.document_type?.replaceAll('_', ' ')}</td><td>{row.document_number || row.vendors?.name || '—'}</td><td>{row.document_date}</td><td>{currency(row.base_total_amount || row.total_amount, row.currency)}</td><td>{row.status}</td></tr>)}{!rows.length && <Empty cols="5" />}</tbody></table>; }
function InventoryTable({ items = [] }) { return <table><thead><tr><th>SKU</th><th>Type</th><th>Available</th><th>Reserved</th><th>Average cost</th><th>Reorder point</th></tr></thead><tbody>{items.map(item => { const balances = item.stock_balances || []; return <tr key={item.id}><td>{item.sku}<br /><small>{item.product_name}</small></td><td>{item.item_type?.replaceAll('_', ' ')}</td><td>{item.ledger_available ?? sum(balances, 'available')}</td><td>{sum(balances, 'reserved')}</td><td>{currency(item.average_cost)}</td><td>{item.reorder_point}</td></tr>; })}{!items.length && <Empty cols="6" />}</tbody></table>; }
function BomTable({ rows = [] }) { return <table><thead><tr><th>Finished item</th><th>Revision</th><th>Status</th><th>Basis</th><th>Effective from</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.inventory_items?.sku || row.finished_item_id}</td><td>{row.revision}</td><td>{row.status}</td><td>{row.quantity_basis}</td><td>{row.effective_from || '—'}</td></tr>)}{!rows.length && <Empty cols="5" />}</tbody></table>; }
function WorkOrderTable({ rows = [] }) { return <table><thead><tr><th>Work order</th><th>Finished good</th><th>Revision</th><th>Planned</th><th>Completed</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.work_order_number}</td><td>{row.inventory_items?.sku || '—'}</td><td>{row.boms?.revision || '—'}</td><td>{row.planned_quantity}</td><td>{row.completed_quantity}</td><td>{row.status?.replaceAll('_', ' ')}</td></tr>)}{!rows.length && <Empty cols="6" />}</tbody></table>; }
function ClaimTable({ rows = [] }) { return <table><thead><tr><th>Claim</th><th>Employee</th><th>Purpose</th><th>Amount</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.claim_number}</td><td>{row.users?.full_name || row.users?.email || '—'}</td><td>{row.business_purpose}</td><td>{currency(row.finance_documents?.total_amount, row.finance_documents?.currency)}</td><td>{row.status?.replaceAll('_', ' ')}</td></tr>)}{!rows.length && <Empty cols="5" />}</tbody></table>; }
function Empty({ cols }) { return <tr><td colSpan={cols} className="empty">No records yet.</td></tr>; }
function sum(rows, field) { return rows.reduce((total, row) => total + Number(row[field] || 0), 0); }
function currency(value, currencyCode = 'INR') { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: currencyCode || 'INR', maximumFractionDigits: 2 }).format(Number(value || 0)); }
