'use client';
import { useState } from 'react';
import { PERMISSION_GROUPS, ROLE_TEMPLATES } from '@/lib/access-control';

export function UserManagement({ initialUsers, audit }) {
  const [users, setUsers] = useState(initialUsers); const [notice, setNotice] = useState('');
  async function create(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({full_name:form.get('full_name'),email:form.get('email'),role:form.get('role'),custom_permissions:{}})}); const data=await response.json(); if(!data.ok) return setNotice(data.error); setUsers([...users,data.user]); setNotice(`Created. Temporary password: ${data.temporary_password} — share it securely, then have the user reset it.`); event.currentTarget.reset(); }
  async function update(user, patch) { const response=await fetch(`/api/admin/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...user,...patch})}); const data=await response.json(); if(!data.ok) return setNotice(data.error); if(data.user) setUsers(users.map(item=>item.id===user.id?data.user:item)); setNotice(patch.action==='reset_password'?'Password-reset email sent.':'User access updated.'); }
  return <div className="adminUsers"><section className="panel"><div className="panelHeader"><h2>Add user</h2></div><div className="panelBody"><form className="userCreate" onSubmit={create}><input name="full_name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email address" required/><select name="role" defaultValue="viewer">{Object.keys(ROLE_TEMPLATES).map(role=><option value={role} key={role}>{role.replaceAll('_',' ')}</option>)}</select><button>Add user</button></form>{notice?<p className="muted">{notice}</p>:null}</div></section><section className="panel" style={{marginTop:18}}><div className="panelHeader"><h2>Users</h2></div><div className="panelBody">{users.map(user=><UserCard key={user.id} user={user} onUpdate={update}/>)}</div></section><section className="panel" style={{marginTop:18}}><div className="panelHeader"><h2>Access audit</h2></div><div className="panelBody detailList">{audit.length?audit.map(entry=><div className="detailRow" key={entry.id}><span>{new Date(entry.created_at).toLocaleString('en-IN')}</span><strong>{entry.action.replaceAll('_',' ')}</strong></div>):<p className="muted">No access changes recorded yet.</p>}</div></section></div>;
}
function UserCard({ user, onUpdate }) { const [role,setRole]=useState(user.role); const [active,setActive]=useState(user.active); const [permissions,setPermissions]=useState(user.custom_permissions||{}); return <article className="userCard"><div><strong>{user.full_name||user.email}</strong><p className="muted">{user.email} · Last sign-in: {user.last_sign_in_at?new Date(user.last_sign_in_at).toLocaleString('en-IN'):'Never'}</p></div><div className="userControls"><select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(ROLE_TEMPLATES).map(key=><option value={key} key={key}>{key.replaceAll('_',' ')}</option>)}</select><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active</label><button className="secondary" onClick={()=>onUpdate(user,{role,active,custom_permissions:permissions})}>Save</button><button className="secondary" onClick={()=>onUpdate(user,{action:'reset_password'})}>Reset password</button></div><details><summary>Custom permissions</summary><div className="permissionGrid">{PERMISSION_GROUPS.flatMap(([module,label,actions])=>actions.map(action=>{const key=`${module}.${action}`;return <label key={key}><input type="checkbox" checked={permissions[key]===true} onChange={e=>setPermissions({...permissions,[key]:e.target.checked})}/>{label}: {action}</label>}))}</div></details></article>; }
